// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20260203093002_initDB")]
    partial class initDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.NguoiDung.nguoi_dung", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("NGAY_CHINH_SUA")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_CHINH_SUA");

                    b.Property<DateTime?>("NGAY_TAO")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_TAO");

                    b.Property<string>("NGUOI_CHINH_SUA")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NGUOI_CHINH_SUA");

                    b.Property<string>("NGUOI_TAO")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NGUOI_TAO");

                    b.Property<Guid?>("anh_dai_dien_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ANH_DAI_DIEN_ID");

                    b.Property<Guid?>("don_vi_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DON_VI_ID");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMAIL");

                    b.Property<int?>("gioi_tinh")
                        .HasColumnType("int")
                        .HasColumnName("GIOI_TINH");

                    b.Property<bool>("is_super_admin")
                        .HasColumnType("bit")
                        .HasColumnName("IS_SUPER_ADMIN");

                    b.Property<int?>("loai_don_vi")
                        .HasColumnType("int")
                        .HasColumnName("LOAI_DON_VI");

                    b.Property<string>("mat_khau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MAT_KHAU");

                    b.Property<string>("salt_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SALT_CODE");

                    b.Property<string>("so_dien_thoai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SO_DIEN_THOAI");

                    b.Property<int?>("so_lan_dang_nhap_that_bai")
                        .HasColumnType("int")
                        .HasColumnName("SO_LAN_DANG_NHAP_THAT_BAI");

                    b.Property<string>("tai_khoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TAI_KHOAN");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TEN");

                    b.Property<DateTime?>("thoi_gian_cap_nhat_mat_khau")
                        .HasColumnType("datetime2")
                        .HasColumnName("THOI_GIAN_CAP_NHAT_MAT_KHAU");

                    b.Property<DateTime?>("thoi_gian_tam_khoa_tai_khoan")
                        .HasColumnType("datetime2")
                        .HasColumnName("THOI_GIAN_TAM_KHOA_TAI_KHOAN");

                    b.HasKey("ID");

                    b.ToTable("nguoi_dung", "admin");
                });
#pragma warning restore 612, 618
        }
    }
}
